### ISSUE TITLE
django validation in models vs. validation in serializers

### ISSUE THREAD

**Issue by zxenia** [c3g/chord_metadata_service#99]
pros? cons?

**Comment by davidlougheed** [comment]
there's a few cons to not doing validation in the model:

1. technically, through other mechanisms, we can introduce invalid models to the database (creating them not through the serializers)
2. we don't have a single place where we can see all the restrictions on a model (have to look at the model AND the serializer)

are there advantages to doing validation in the serializer?

**Comment by zxenia** [comment]
Yeah, I was thinking the same. Especially if our ingestion works directly on the database.

The only advantage I can think of in our case is that our database model is quite stable, yet some of the schemas can be changed: when we change it in serializers we change it on a higher level and don't touch models that much (even if it won't change the actual database architecture).

Anyway, since we have ingestion that works via django models API I think we need to refactor the validation and move it to the models.

**Comment by zxenia** [comment]
The validation was moved to the models level.
